<?php
/**
 * AdminApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AnythingLLM Developer API
 *
 * API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdminApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1AdminInviteIdDelete
     *
     * .
     *
     */
    public function testV1AdminInviteIdDelete()
    {
    }

    /**
     * Test case for v1AdminInviteNewPost
     *
     * .
     *
     */
    public function testV1AdminInviteNewPost()
    {
    }

    /**
     * Test case for v1AdminInvitesGet
     *
     * .
     *
     */
    public function testV1AdminInvitesGet()
    {
    }

    /**
     * Test case for v1AdminIsMultiUserModeGet
     *
     * .
     *
     */
    public function testV1AdminIsMultiUserModeGet()
    {
    }

    /**
     * Test case for v1AdminPreferencesGet
     *
     * .
     *
     */
    public function testV1AdminPreferencesGet()
    {
    }

    /**
     * Test case for v1AdminPreferencesPost
     *
     * .
     *
     */
    public function testV1AdminPreferencesPost()
    {
    }

    /**
     * Test case for v1AdminUsersGet
     *
     * .
     *
     */
    public function testV1AdminUsersGet()
    {
    }

    /**
     * Test case for v1AdminUsersIdDelete
     *
     * .
     *
     */
    public function testV1AdminUsersIdDelete()
    {
    }

    /**
     * Test case for v1AdminUsersIdPost
     *
     * .
     *
     */
    public function testV1AdminUsersIdPost()
    {
    }

    /**
     * Test case for v1AdminUsersNewPost
     *
     * .
     *
     */
    public function testV1AdminUsersNewPost()
    {
    }

    /**
     * Test case for v1AdminWorkspaceChatsPost
     *
     * .
     *
     */
    public function testV1AdminWorkspaceChatsPost()
    {
    }

    /**
     * Test case for v1AdminWorkspacesWorkspaceIdUpdateUsersPost
     *
     * .
     *
     */
    public function testV1AdminWorkspacesWorkspaceIdUpdateUsersPost()
    {
    }
}
