<?php
/**
 * DocumentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AnythingLLM Developer API
 *
 * API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1DocumentAcceptedFileTypesGet
     *
     * .
     *
     */
    public function testV1DocumentAcceptedFileTypesGet()
    {
    }

    /**
     * Test case for v1DocumentDocNameGet
     *
     * .
     *
     */
    public function testV1DocumentDocNameGet()
    {
    }

    /**
     * Test case for v1DocumentUploadLinkPost
     *
     * .
     *
     */
    public function testV1DocumentUploadLinkPost()
    {
    }

    /**
     * Test case for v1DocumentUploadPost
     *
     * .
     *
     */
    public function testV1DocumentUploadPostForm()
    {
    }

    /**
     * Test case for v1DocumentsGet
     *
     * .
     *
     */
    public function testV1DocumentsGet()
    {
    }
}
