<?php
/**
 * WorkspacesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AnythingLLM Developer API
 *
 * API endpoints that enable programmatic reading, writing, and updating of your AnythingLLM instance. UI supplied by Swagger.io.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkspacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WorkspacesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1WorkspaceNewPost
     *
     * .
     *
     */
    public function testV1WorkspaceNewPost()
    {
    }

    /**
     * Test case for v1WorkspaceSlugChatPost
     *
     * .
     *
     */
    public function testV1WorkspaceSlugChatPost()
    {
    }

    /**
     * Test case for v1WorkspaceSlugChatsGet
     *
     * .
     *
     */
    public function testV1WorkspaceSlugChatsGet()
    {
    }

    /**
     * Test case for v1WorkspaceSlugDelete
     *
     * .
     *
     */
    public function testV1WorkspaceSlugDelete()
    {
    }

    /**
     * Test case for v1WorkspaceSlugGet
     *
     * .
     *
     */
    public function testV1WorkspaceSlugGet()
    {
    }

    /**
     * Test case for v1WorkspaceSlugStreamChatPost
     *
     * .
     *
     */
    public function testV1WorkspaceSlugStreamChatPost()
    {
    }

    /**
     * Test case for v1WorkspaceSlugUpdateEmbeddingsPost
     *
     * .
     *
     */
    public function testV1WorkspaceSlugUpdateEmbeddingsPost()
    {
    }

    /**
     * Test case for v1WorkspaceSlugUpdatePost
     *
     * .
     *
     */
    public function testV1WorkspaceSlugUpdatePost()
    {
    }

    /**
     * Test case for v1WorkspacesGet
     *
     * .
     *
     */
    public function testV1WorkspacesGet()
    {
    }
}
